### PR TITLE
docs: add Chinese translation

### PR DESCRIPTION
**Pull request by BryanYin**

### CODE REVIEW

**Comment by vyacheslav-pushkin** [comment]
Hi @BryanYin,

The [same](https://github.com/cuba-platform/frontend/pull/331#issuecomment-737130977) comment about commit messages.

Also, could you please exclude unrelated changes and only include the commit with the new JSON file to this PR? Thanks.

**Comment by BryanYin** [comment]
the new commit fixed commit message and removed zh-cn.json. #342 is for the json file.

**Comment by vyacheslav-pushkin** [comment]
Hi @BryanYin,

You need to replace these commits:

image

They are causing CI build to fail.

**Comment by BryanYin** [comment]
@vyacheslav-pushkin please check if it's ok now.

**Pull request merged**
